refactor: generate function refactored to reduce cognitive complexity
asyncapi/generator pull request #1047
Opened 2023-10-08 13:42 UTC by swastiksuvam55

`generate` function refactored to smaller individual functions to reduce cognitive complexity

2023-10-09 07:46 UTC, jonaslagoni requested changes
Just a few comments 💪

2023-10-09 07:46 UTC, jonaslagoni commented on lib/generator.js
> +  /* async generate(asyncapiDocument, parseOptions = {}) {
Please remove any commented out code 🙂

2023-10-09 07:46 UTC, jonaslagoni commented on lib/generator.js
> +  // Main method for generating code based on AsyncAPI document
Please switch to the jsdoc comments (for all functions) and use the same as the old one for the function 🙂

2023-10-09 07:46 UTC, jonaslagoni commented
You also have a linting issue 🙂

2023-10-09 12:27 UTC, swastiksuvam55 commented
@jonaslagoni  Thank you for the much-needed feedback, I've made the changes can you please review it again?

2023-10-09 14:22 UTC, jonaslagoni requested changes
Few more changes is needed 🙂

2023-10-09 14:22 UTC, jonaslagoni commented on lib/generator.js
> +  // eslint-disable-next-line sonarjs/cognitive-complexity
Please remove this 🙂

2023-10-09 14:22 UTC, jonaslagoni commented on lib/generator.js
> +
No new lines between the jsdoc and function 🙂

2023-10-09 14:22 UTC, jonaslagoni commented on lib/generator.js
> -   * }
You can leave the different examples, no need to remove it 🙂

2023-10-09 14:22 UTC, jonaslagoni commented on lib/generator.js
> +  // Setup the output based on the configured options
No need for this.

2023-10-09 14:22 UTC, jonaslagoni commented on lib/generator.js
> +  */
Incorrect indentation 🙂

2023-10-09 14:22 UTC, jonaslagoni commented on lib/generator.js
> +  */
Incorrect indentation

2023-10-10 09:18 UTC, merged

2023-10-10 09:20 UTC, jonaslagoni commented
@all-contributors please add @swastiksuvam55 for code