feat: added $$operation$$ file template
asyncapi/generator pull request #1117
Opened 2024-02-08 21:26 UTC by lukas-mertens

**Description**

I added `$$operation$$` as a file template.

**Related issue(s)**

#1116

2024-02-16 12:33 UTC, lukas-mertens commented
@jonaslagoni I see that you introduced the v3 support. Does it make any sense what I am suggesting or am I missing something?

2024-03-11 09:06 UTC, jonaslagoni requested changes
Seems like the tests are failing :v:

2024-03-11 13:09 UTC, derberg commented on lib/generator.js
> +        operation: convertCollectionToObject(asyncapiDocument.allOperations()),
shouldn't you use `convertMapToObject` like other parts?

2024-03-19 08:53 UTC, derberg commented
@jonaslagoni yeah, to be honest I did not recall `file templates` are actually useful for nunjucks only 😄 

we have at least comparizon from the perspective of "template for templates". So we see file templates in use in https://github.com/asyncapi/template-for-generator-templates/tree/nunjucks/template/schemas in times of nunjucks and then after conversion to react https://github.com/asyncapi/template-for-generator-templates/blob/master/template/schemas/schema.js

just to be sure, @lukas-mertens what templating engine are you using?

2024-03-19 09:58 UTC, lukas-mertens commented
@derberg Yeah, I am using the old one. I didn't see it in any documentation that a new one exists and I was building my template based on https://github.com/asyncapi/dotnet-nats-template/tree/master

I didn't know it is that outdated back then. It would be really nice to have a few reference-implementations based on the new api version and new renderer

2024-03-25 13:11 UTC, derberg commented
actually https://github.com/asyncapi/dotnet-nats-template/tree/master runs on new engine, the `react` one

also in docs that talk about template development we reference this template example implementation -> https://github.com/asyncapi/template-for-generator-templates

is the source code of your template somewhere available?

my assumption is you use `react` so you do not need file templates. Have a look at examples I shared in previous comment and lemme know

2024-04-11 14:06 UTC, derberg commented
@lukas-mertens hey, did you have a chance to have a look at it?

2024-04-24 09:25 UTC, derberg commented
closing this PR

we should not add more features to Nunjucks.

and for React - functionality is already in place - we just need to properly document it -> https://github.com/asyncapi/generator/issues/1199

2024-04-24 09:25 UTC, closed without merging