feat: file-templates as array in React render engine
asyncapi/generator pull request #518
Opened 2021-03-01 08:48 UTC by magicmatatjahu

**Description**

- Render an array of File component from React render engine - file templates feature.
- Add documentation for new feature.

**Related issue(s)**
Part of https://github.com/asyncapi/generator-react-sdk/issues/10

2021-03-02 11:46 UTC, jonaslagoni requested changes
Just some small comments. In hindsight, I should have added tests for the renderer when first integrating the feature. Gonna create a follow up issue about that.

2021-03-02 11:46 UTC, jonaslagoni commented on docs/authoring.md
> +The above way of rendering **file templates** works for both `nunjucks` and `react` render engine, but `react` also has another, more generic way to render multiple files. It is enough to return an a
```suggestion
The above way of rendering **file templates** works for both `nunjucks` and `react` render engines, but `react` also has another, more generic way to render multiple files. It is enough to return an array of `File` components in the rendering component. See the following example:
```

2021-03-02 11:46 UTC, jonaslagoni commented on docs/authoring.md
> +```
I think this is too large of an example, what about: 

```suggestion
```tsx
export default function({ asyncapi }) {
  return [
    <File name={`file1.html`}>//Content</File>,
    <File name={`file2.html`}>//Content</File>
  ]
}
```
```

2021-03-02 12:02 UTC, jonaslagoni commented
@magicmatatjahu you have a problem with SonarCloud 😄

2021-03-02 12:09 UTC, derberg commented
@magicmatatjahu will you also do a follow-up in the template for templates, to use this new way for file templates?

2021-03-02 12:20 UTC, magicmatatjahu commented
@derberg Of course, I will, but I wanna wait for merge your PR to write tests for an array of Files - your PR has architecture for tests.

2021-03-03 11:30 UTC, jonaslagoni commented
@magicmatatjahu you have a little problem with checks 😄

2021-03-03 11:37 UTC, derberg commented
@magicmatatjahu you need to increase timeouts in the test project tests to a larger number, these tests are really long-running :(

2021-03-04 10:45 UTC, jonaslagoni submitted a review, later dismissed
👍

2021-03-04 11:14 UTC, jonaslagoni approved these changes

2021-03-04 11:33 UTC, jonaslagoni approved these changes

2021-03-04 11:34 UTC, merged