fix: broken links in readme file
asyncapi/generator pull request #885
Opened 2022-12-14 05:02 UTC by sambhavgupta0705

**Description**

-Updated the broken links in readme file

**Related issue(s)**

Resolves #873

2022-12-14 05:04 UTC, sambhavgupta0705 commented
cc @derberg @Florence-Njeri @jonaslagoni

2022-12-14 05:10 UTC, Florence-Njeri requested changes

2022-12-14 05:10 UTC, Florence-Njeri commented on README.md
> +Learn to install the AsyncAPI CLI from the [installation guide](https://github.com/asyncapi/generator/blob/master/docs/installation-guide.md).
```suggestion
Learn to install the AsyncAPI CLI from the [installation guide](docs/installation-guide.md).
```

2022-12-14 05:10 UTC, Florence-Njeri commented on README.md
> +Learn more about different ways of using the CLI from the [usage document](https://github.com/asyncapi/generator/blob/master/docs/usage.md).
```suggestion
Learn more about different ways of using the CLI from the [usage document](docs/usage.md).
```

2022-12-14 05:10 UTC, Florence-Njeri commented on README.md
> +Learn more about versioning from the [versioning document](https://github.com/asyncapi/generator/blob/master/docs/versioning.md).
```suggestion
Learn more about versioning from the [versioning document](docs/versioning.md).
```

2022-12-14 05:12 UTC, Florence-Njeri commented
> cc @derberg @Florence-Njeri @jonaslagoni

Hey, @sambhavgupta0705 good job fixing the broken links. I have left a few suggestions on the fixes

2022-12-14 05:25 UTC, sambhavgupta0705 commented
Hi @Florence-Njeri made the suggested changes

2022-12-15 09:23 UTC, pratik2315 commented
Hey @sambhavgupta0705 i dont see any broken links in the readme🤔

2022-12-15 09:27 UTC, sambhavgupta0705 commented
@pratik2315 there were 3 links in which  `docs/` prefix was missing

2022-12-15 09:42 UTC, pratik2315 commented
> @pratik2315 there were 3 links in which `docs/` prefix was missing

Oh okay👍

2022-12-15 12:46 UTC, derberg commented
@sambhavgupta0705 when you followup on a review and you are ready for another round from initial reviewer, then please always remember to use the circle-arrow icon 👇🏼 

![Screenshot 2022-12-15 at 13 45 58](https://user-images.githubusercontent.com/6995927/207862635-991b79ef-c64e-4956-9c08-c02aa7a17bde.png)

2022-12-15 12:50 UTC, Florence-Njeri approved these changes

2022-12-15 13:25 UTC, sambhavgupta0705 commented
> @sambhavgupta0705 when you followup on a review and you are ready for another round from initial reviewer, then please always remember to use the circle-arrow icon 👇🏼
> 
> ![Screenshot 2022-12-15 at 13 45 58](https://user-images.githubusercontent.com/6995927/207862635-991b79ef-c64e-4956-9c08-c02aa7a17bde.png)

ohk ,will take care of it from now

2022-12-15 14:24 UTC, derberg approved these changes

2022-12-15 14:27 UTC, derberg commented
@sambhavgupta0705 I updated PR title to `docs: `. It is important to remember to use conventional commits properly. If we would merge this PR with `fix:` prefix, or `feat:`, that would trigger release pipeline and patch release for generator would go out, but because of links fix it is not needed.

@Florence-Njeri wanna merge? you know the comment that will trigger that? just add it once all the check are green and the status of PR shows green

2022-12-15 17:58 UTC, sambhavgupta0705 commented
> @sambhavgupta0705 I updated PR title to `docs: `. It is important to remember to use conventional commits properly. If we would merge this PR with `fix:` prefix, or `feat:`, that would trigger release pipeline and patch release for generator would go out, but because of links fix it is not needed.
> 
> @Florence-Njeri wanna merge? you know the comment that will trigger that? just add it once all the check are green and the status of PR shows green

Okay @derberg ,will take care of this

2022-12-20 06:25 UTC, Florence-Njeri commented
/rtm

2022-12-20 06:26 UTC, merged